In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=["the glass of milk",
      "the glass of juice",
      "the cup of tea",
      "i am a good developer",
      "understand the meaning of the words",
      "your vidios are good"]

In [3]:
#vocabary siz
voc_size=10000

In [4]:
one_hot_repres=[one_hot(words,voc_size)for words in sent] 
one_hot_repres

[[3522, 2887, 8326, 3624],
 [3522, 2887, 8326, 8838],
 [3522, 1032, 8326, 926],
 [4795, 332, 2172, 7705, 2305],
 [2549, 3522, 9420, 8326, 3522, 4474],
 [9498, 2531, 8303, 7705]]

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
Embedding_doc=pad_sequences(one_hot_repres,padding='pre',maxlen=sent_length)#pre=we are saying the the rest of the size should be covered 
print(Embedding_doc)
#"pre" will write the "0"s at the first and "Post" will write the "0"s at the last

[[   0    0    0    0 3522 2887 8326 3624]
 [   0    0    0    0 3522 2887 8326 8838]
 [   0    0    0    0 3522 1032 8326  926]
 [   0    0    0 4795  332 2172 7705 2305]
 [   0    0 2549 3522 9420 8326 3522 4474]
 [   0    0    0    0 9498 2531 8303 7705]]


In [8]:
dim=10


In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile("adam","mse")

c:\Users\Admin\Desktop\RNN\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(Embedding_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step


array([[[-0.01055062,  0.01708772, -0.00431848, -0.00262041,
          0.01199009,  0.03990289,  0.03635547, -0.01843046,
          0.02805022,  0.02878852],
        [-0.01055062,  0.01708772, -0.00431848, -0.00262041,
          0.01199009,  0.03990289,  0.03635547, -0.01843046,
          0.02805022,  0.02878852],
        [-0.01055062,  0.01708772, -0.00431848, -0.00262041,
          0.01199009,  0.03990289,  0.03635547, -0.01843046,
          0.02805022,  0.02878852],
        [-0.01055062,  0.01708772, -0.00431848, -0.00262041,
          0.01199009,  0.03990289,  0.03635547, -0.01843046,
          0.02805022,  0.02878852],
        [ 0.00721567, -0.03048592, -0.03091794,  0.00449817,
          0.04907979, -0.0231598 ,  0.02111608, -0.01913499,
         -0.0201153 , -0.02746835],
        [ 0.04578202, -0.04088675, -0.03723197,  0.00897779,
         -0.04199784,  0.01841425,  0.02421013,  0.04895382,
          0.00094467,  0.03172976],
        [-0.00720755,  0.0454143 ,  0.03009485, -0.0

In [12]:
Embedding_doc[0]

array([   0,    0,    0,    0, 3522, 2887, 8326, 3624], dtype=int32)

In [13]:
print(model.predict(np.expand_dims(Embedding_doc[0], axis=0)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
[[[-0.01055062  0.01708772 -0.00431848 -0.00262041  0.01199009
    0.03990289  0.03635547 -0.01843046  0.02805022  0.02878852]
  [-0.01055062  0.01708772 -0.00431848 -0.00262041  0.01199009
    0.03990289  0.03635547 -0.01843046  0.02805022  0.02878852]
  [-0.01055062  0.01708772 -0.00431848 -0.00262041  0.01199009
    0.03990289  0.03635547 -0.01843046  0.02805022  0.02878852]
  [-0.01055062  0.01708772 -0.00431848 -0.00262041  0.01199009
    0.03990289  0.03635547 -0.01843046  0.02805022  0.02878852]
  [ 0.00721567 -0.03048592 -0.03091794  0.00449817  0.04907979
   -0.0231598   0.02111608 -0.01913499 -0.0201153  -0.02746835]
  [ 0.04578202 -0.04088675 -0.03723197  0.00897779 -0.04199784
    0.01841425  0.02421013  0.04895382  0.00094467  0.03172976]
  [-0.00720755  0.0454143   0.03009485 -0.01763765  0.04131963
    0.00047874 -0.01541661 -0.02650757 -0.01300872  0.03202971]
  [ 0.01312478 -0.01999462  0.04654172 -0.00190496  0.0185773
    0.02603